version: 2.1

workflows:
  test:
    jobs:
      - build-run-linux:
          context: hello-world-demos

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
    - build-run-linux:
        context: hello-world-demos

# This CI build ensures that the demo both compiles and works correctly. For the runtime test,
# we use an SDK key and flag key that are passed in via the CircleCI project configuration;
# the flag is configured to return a true value.

jobs:
  build-run-linux:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - run:
          name: insert SDK key and flag key into demo code
          command: |
            sed -i.bak "s/\$sdkKey *= *\".*\"/\$sdkKey = \"${LD_HELLO_WORLD_SDK_KEY}\"/" index.php
            sed -i.bak "s/\$featureFlagKey *= *\".*\"/\$featureFlagKey = \"${LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE}\"/" index.php
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run hello
          command: php index.php | tee output.txt
      - run:
          name: Check output
          command: |
            grep "is true for this context" output.txt || (echo "Flag did not evaluate to expected true value" && exit 1)
